### ISSUE TITLE
Why not provide a pdf and html version of all the catergories to download?

### ISSUE THREAD

**Issue by sahilshekhawat** [CuriousLearner/GeeksForGeeksScrapper#2]
I think it will be easy for users.

**Comment by CuriousLearner** [comment]
Because that content does not belong to us. It is the content they've written with so much hard-work.
This script is there just to facilitate some geeks who aren't able to connect to 24 X 7, but want to learn from G4G. I highly encourage any one to read from their site if they're connected to Internet.

I hope that answers your question :)

**Comment by CuriousLearner** [comment]
If you still want to discuss, consider re-opening this issue.

Thanks!
